apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-exporter
  labels:
    app: fluxcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-exporter
  template:
    metadata:
      labels:
        app: network-exporter
    spec:
      containers:
      - name: network-exporter
        image: network-exporter:latest
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 250m
            memory: 64Mi
          requests:
            cpu: 125m
            memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: network-exporter
  labels:
    app: network-exporter
  annotations:
    "prometheus.io/port": "8080"
    "prometheus.io/scrape": "true"
spec:
  type: ClusterIP
  selector:
    app: network-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: network-exporter
  labels:
    app: network-exporter
spec:
  selector:
    matchLabels:
      app: network-exporter
  endpoints:
    - port: metrics